In [0]:
import numpy as np

In [0]:
my_list = [0,1,2,3,4,5,6,7]

In [0]:
my_array = np.array(my_list)

In [0]:
print(my_array)

[0 1 2 3 4 5 6 7]


In [0]:
np.argmax(my_array)

7

In [0]:
np.argmin(my_array)

0

In [0]:
print(my_array)

[0 1 2 3 4 5 6 7]


In [0]:
print(my_array[:4])

[0 1 2 3]


In [0]:
print(my_array[4:])

[4 5 6 7]


In [0]:
print(my_array[4:6])

[4 5]


In [0]:
print(my_array.shape)

(8,)


In [0]:
reshaped_array = np.reshape(my_array, (2,4))

In [0]:
print(reshaped_array)

[[0 1 2 3]
 [4 5 6 7]]


In [0]:
reshaped_array = np.reshape(my_array, (4,2))

In [0]:
print(reshaped_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
